ALTER TABLE public.trades 
ADD COLUMN IF NOT EXISTS stop_loss DECIMAL(15, 5),
ADD COLUMN IF NOT EXISTS take_profit DECIMAL(15, 5),
ADD COLUMN IF NOT EXISTS close_reason TEXT,
ADD COLUMN IF NOT EXISTS close_time TIMESTAMP WITH TIME ZONE;
